In [11]:
from benchmark.data_provider.data_loader import Dataset_Custom, BenchZeroShotDataset
from torch.utils.data import DataLoader
from benchmark.data_provider.data_factory import data_provider
import numpy as np
import argparse
from benchmark.utils.arg_resolver import resolve_transformer_args, _model_is_transformer, setting_string, resolve_args

In [23]:
dataset1 = Dataset_Custom(root_path='/home/jovyan/kkuvshinova/ForecastPFN_accelerate/academic_data/ETT-small', flag='test', timeenc=1)

In [16]:
dataset1.seq_len

384

In [24]:
dataset1.__dict__

{'seq_len': 384,
 'label_len': 96,
 'pred_len': 96,
 'set_type': 2,
 'features': 'S',
 'target': 'OT',
 'scale': True,
 'timeenc': 1,
 'freq': 'h',
 'scaler': StandardScaler(),
 'train_budget': None,
 'root_path': '/home/jovyan/kkuvshinova/ForecastPFN_accelerate/academic_data/ETT-small',
 'data_path': 'ETTh1_.csv',
 'data_stamp_original':                       date  Unnamed: 0    HUFL   HULL   MUFL   MULL   LUFL  \
 13552  2018-01-16 16:00:00       13552   9.578  2.009  5.899  0.533  3.686   
 13553  2018-01-16 17:00:00       13553  12.257  2.679  7.995  0.817  4.447   
 13554  2018-01-16 18:00:00       13554  11.855  2.210  7.569  0.746  4.295   
 13555  2018-01-16 19:00:00       13555  11.588  2.076  7.427  0.569  4.142   
 13556  2018-01-16 20:00:00       13556  10.784  2.210  6.752  0.569  4.112   
 ...                    ...         ...     ...    ...    ...    ...    ...   
 17415  2018-06-26 15:00:00       17415  -1.674  3.550 -5.615  2.132  3.472   
 17416  2018-06-26 16:00:00 

In [32]:
import tensorflow as tf
tf.convert_to_tensor(tf.ones([5, 1], tf.int32).unsqueeze(0).repeat(5, 1, 1), dtype=tf.int64)

AttributeError: 'tensorflow.python.framework.ops.EagerTensor' object has no attribute 'unsqueeze'

In [35]:
tf.ones([5, 1], tf.float64).unsqueeze(0)

AttributeError: 'tensorflow.python.framework.ops.EagerTensor' object has no attribute 'unsqueeze'

In [25]:
data_loader = DataLoader(
    dataset1,
    batch_size=1,
    shuffle=False,
    num_workers=4,
    drop_last=False)

In [26]:
next(iter(data_loader))

[tensor([[[-1.4631],
          [-1.5220],
          [-1.5220],
          [-1.4126],
          [-1.3873],
          [-1.3788],
          [-1.3030],
          [-1.5305],
          [-1.6064],
          [-1.5389],
          [-1.5137],
          [-1.3620],
          [-1.2693],
          [-1.2271],
          [-1.1597],
          [-1.2356],
          [-1.2946],
          [-1.1850],
          [-1.1177],
          [-1.1008],
          [-1.2102],
          [-1.3198],
          [-1.3620],
          [-1.2609],
          [-1.1766],
          [-1.2524],
          [-1.3451],
          [-1.3704],
          [-1.3282],
          [-1.2777],
          [-1.3451],
          [-1.3535],
          [-1.4041],
          [-1.3873],
          [-1.4041],
          [-1.4293],
          [-1.4631],
          [-1.4378],
          [-1.4884],
          [-1.4378],
          [-1.4378],
          [-1.4378],
          [-1.4547],
          [-1.4378],
          [-1.4968],
          [-1.4378],
          [-1.4126],
          [-1

In [9]:
def parse():

    parser = argparse.ArgumentParser(
        description='Comparing performance of ForecastPFN to other Time Series Benchmarks')

    parser.add_argument('--is_training', type=int, default=0, help='status')
    parser.add_argument('--use_gpu', type=bool, default=True, help='status')
    parser.add_argument('--itr', type=int, default=5, help='status')

    # model settings
    parser.add_argument('--model', type=str, default='ForecastPFN',
                        help='model name, options: [ForecastPFN, FEDformer, Autoformer, Informer, Transformer, Arima, Prophet]')

    # forecasting task
    parser.add_argument('--seq_len', type=int, default=384,
                        help='input sequence length')
    parser.add_argument('--label_len', type=int,
                        default=96, help='start token length')
    parser.add_argument('--pred_len', type=int, default=96,
                        help='prediction sequence length')

    # parser.add_argument('--time_budget', type=int,
    #                     help='amount of time budget to train the model')
    # parser.add_argument('--train_budget', type=int,
    #                     help='length of training sequence')

    # data loader
    parser.add_argument('--data', type=str,
                        default='ETTh1', help='dataset type')
    parser.add_argument('--root_path', type=str,
                        default='../academic_data/ETT-small/', help='root path of the data file')
    parser.add_argument('--data_path', type=str,
                        default='ETTh1_.csv', help='data file')
    parser.add_argument('--target', type=str,
                        default='OT', help='name of target column')
    parser.add_argument('--scale', type=bool, default=True,
                        help='scale the time series with sklearn.StandardScale()')

    # ForecastPFN
    parser.add_argument('--model_path', type=str, default='../saved_weights/',
                        help='encoder input size')
    parser.add_argument('--scaler', type=str, default='standard',
                        help='scale the test series with sklearn.StandardScale()')

    # Metalearn
    parser.add_argument('--metalearn_freq', type=str,
                        help='which type of model should be used for the Metalearn model. Typically M, W, or D.')
    return parser

In [10]:
parser = parse()
args = parser.parse_args()
args = resolve_args(args)

usage: ipykernel_launcher.py [-h] [--is_training IS_TRAINING]
                             [--use_gpu USE_GPU] [--itr ITR] [--model MODEL]
                             [--seq_len SEQ_LEN] [--label_len LABEL_LEN]
                             [--pred_len PRED_LEN] [--data DATA]
                             [--root_path ROOT_PATH] [--data_path DATA_PATH]
                             [--target TARGET] [--scale SCALE]
                             [--model_path MODEL_PATH] [--scaler SCALER]
                             [--metalearn_freq METALEARN_FREQ]
ipykernel_launcher.py: error: unrecognized arguments: --ip=127.0.0.1 --stdin=9008 --control=9006 --hb=9005 --Session.signature_scheme="hmac-sha256" --Session.key=b"dc6ad997-58c5-44b8-ac65-6167014f18e9" --shell=9007 --transport="tcp" --iopub=9009 --f=/home/jovyan/.local/share/jupyter/runtime/kernel-v2-347175Fvwj4DSEoA6W.json


SystemExit: 2

In [ ]:
data_set, data_loader = data_provider()

In [2]:
dataset1 = Dataset_Custom(root_path='/home/jovyan/kkuvshinova/ForecastPFN_accelerate/academic_data/ETT-small')
a = dataset1[0]

In [3]:
dataset1.seq_len

384

In [4]:
dataset1.label_len

96

In [5]:
dataset1.pred_len

96

In [6]:
dataset1.train_budget

In [7]:
a[0]

array([[1.70525639],
       [1.37657355],
       [1.37657355],
       [1.04801043],
       [0.67716404],
       [0.58445245],
       [0.77826037],
       [0.82042369],
       [0.64350517],
       [0.13790359],
       [0.44131252],
       [0.45808198],
       [0.34860092],
       [0.27277873],
       [0.39064452],
       [0.12101441],
       [0.38225979],
       [0.34009648],
       [0.52551944],
       [0.2895482 ],
       [0.18845187],
       [0.20534128],
       [0.20534128],
       [0.41603838],
       [0.57606772],
       [0.40753393],
       [0.44969725],
       [0.5339044 ],
       [0.60972659],
       [0.71094263],
       [0.47497139],
       [0.57606772],
       [0.51713471],
       [0.2475046 ],
       [0.55917831],
       [0.37387506],
       [0.54240885],
       [0.46658666],
       [0.60134186],
       [0.68566849],
       [0.52551944],
       [1.09855848],
       [1.14910676],
       [1.38495828],
       [1.31764054],
       [0.71094263],
       [0.67716404],
       [1.317

In [6]:
data

array([[[-1.65172522, -1.65172522, -1.65172522, ..., -1.65172522,
         -1.65172522, -1.65172522]],

       [[-1.64493755, -1.64493755, -1.64493755, ..., -1.64493755,
         -1.64493755, -1.64493755]],

       [[-1.63885194, -1.63885194, -1.63885194, ..., -1.63885194,
         -1.63885194, -1.63885194]],

       ...,

       [[-0.77096854, -0.77096854, -0.77096854, ..., -0.77096854,
         -0.77096854, -0.77096854]],

       [[-0.77120478, -0.77120478, -0.77120478, ..., -0.77120478,
         -0.77120478, -0.77120478]],

       [[-0.77096854, -0.77096854, -0.77096854, ..., -0.77096854,
         -0.77096854, -0.77096854]]])

In [7]:
np.isnan(data).sum()

0

In [8]:
np.isinf(data).sum()

0

In [9]:
data = np.load('/home/jovyan/kkuvshinova/ForecastPFN_accelerate/benchmark/results_history/ETTh1/ForecastPFN_ETTh1_sl36_ll18_pl14_timebudget_None_trainbudget_50_model-path_saved_weights_targetOT_itr_0/true.npy')

In [10]:
np.isnan(data).sum()

0

In [11]:
np.isinf(data).sum()

0

In [14]:
data = np.load('/home/jovyan/kkuvshinova/ForecastPFN_accelerate/benchmark/results_history/ETTh1/ForecastPFN_ETTh1_sl36_ll18_pl14_timebudget_None_trainbudget_50_model-path_saved_weights_targetOT_itr_0/metrics.npy', allow_pickle=True)


libgomp: Invalid value for environment variable OMP_NUM_THREADS


In [15]:
data

array({'metrics': {'mae': 0.227779650408567, 'mse': 0.09279294257578616, 'rmse': 0.3046193404493322, 'mape': 0.3487395024324892, 'mspe': 4.013795182933621}, 'train_timer': None, 'vali_timer': None, 'test_timer': 0.09956669807434082, 'args': Namespace(is_training=0, use_gpu=True, itr=5, model='ForecastPFN', seq_len=36, label_len=18, pred_len=14, time_budget=None, train_budget=50, data='ETTh1', root_path='../academic_data/ETT-small/', data_path='ETTh1_.csv', target='OT', scale=True, model_path='../saved_weights/', scaler=StandardScaler(), metalearn_freq=None, features='S', freq='h', checkpoints='./checkpoints/', embed='timeF', batch_size=512, gpu=0, use_multi_gpu=True, devices='0,1', num_workers=10, model_name='saved_weights', dvices='0,1', device_ids=[0, 1])},
      dtype=object)

In [17]:
data = np.load('/home/jovyan/kkuvshinova/ForecastPFN_accelerate/benchmark/results_history/ETTh1/ForecastPFN_ETTh1_sl36_ll18_pl96_timebudget_None_trainbudget_1_model-path_.._targetHUFL_itr_0/pred.npy')

In [18]:
data

array([[[ 0.75126138,  0.75126138,  0.75126138, ...,  0.75126138,
          0.75126138,  0.75126138]],

       [[ 0.7011685 ,  0.7011685 ,  0.7011685 , ...,  0.7011685 ,
          0.7011685 ,  0.7011685 ]],

       [[ 0.69326071,  0.69326071,  0.69326071, ...,  0.69326071,
          0.69326071,  0.69326071]],

       ...,

       [[-0.4656374 , -0.4656374 , -0.4656374 , ..., -0.4656374 ,
         -0.4656374 , -0.4656374 ]],

       [[-0.4999147 , -0.4999147 , -0.4999147 , ..., -0.4999147 ,
         -0.4999147 , -0.4999147 ]],

       [[-0.51573465, -0.51573465, -0.51573465, ..., -0.51573465,
         -0.51573465, -0.51573465]]])

In [19]:
np.isnan(data).sum()

288

In [20]:
data = np.load('/home/jovyan/kkuvshinova/ForecastPFN_accelerate/benchmark/results_history/ETTh1/ForecastPFN_ETTh1_sl36_ll18_pl96_timebudget_None_trainbudget_1_model-path_.._targetHUFL_itr_0/true.npy')

In [21]:
data

array([[[-0.5921752 ],
        [ 0.9264881 ],
        [ 1.2850153 ],
        ...,
        [-3.3131723 ],
        [-2.9546452 ],
        [-2.3007302 ]],

       [[ 0.9264881 ],
        [ 1.2850153 ],
        [ 1.7701373 ],
        ...,
        [-2.9546452 ],
        [-2.3007302 ],
        [-1.1616936 ]],

       [[ 1.2850153 ],
        [ 1.7701373 ],
        [ 1.6647992 ],
        ...,
        [-2.3007302 ],
        [-1.1616936 ],
        [ 0.8104429 ]],

       ...,

       [[-0.27584606],
        [-0.20199916],
        [-0.13870184],
        ...,
        [-1.4358245 ],
        [-2.0369916 ],
        [-0.72931933]],

       [[-0.20199916],
        [-0.13870184],
        [-0.13870184],
        ...,
        [-2.0369916 ],
        [-0.72931933],
        [ 0.28312278]],

       [[-0.13870184],
        [-0.13870184],
        [ 0.25147408],
        ...,
        [-0.72931933],
        [ 0.28312278],
        [ 0.42026702]]], dtype=float32)